Gemfile
Gemfile.lock

gem installed:
- annotate
- faker
- cloudinary
- carriewave

gem-installed

---

Gemfile
Gemfile.lock
app/models/activity.rb
config/initializers/money.rb
db/migrate/20180227145148_create_activities.rb
db/schema.rb
db/seeds.rb
test/fixtures/activities.yml
test/models/activity_test.rb

done generate + seeds + validations + gem 'money-rails' + enum for active + crash test

Activity model

---

app/models/timeslot.rb
db/migrate/20180228112225_create_timeslots.rb
db/schema.rb
db/seeds.rb
test/fixtures/timeslots.yml
test/models/timeslot_test.rb

timeslot model created:
-generate
-seed 
-validations

timeslot-model

---

app/models/booking.rb
db/migrate/20180228105104_create_bookings.rb
db/schema.rb
db/seeds.rb
test/fixtures/bookings.yml
test/models/booking_test.rb

@EricBoutueil 
DONE:
Model Booking generated
Booking seed created
Validations managed
Model crash tested on console
NOT DONE:
Add column timeslots_id to model Booking
Thanks for your review mate !

generate-model-booking

---

app/models/activity.rb
app/models/booking.rb
app/models/client.rb
app/models/timeslot.rb
app/models/user.rb
db/migrate/20180228150423_add_status_to_timeslots.rb
db/migrate/20180228152839_rename_active_activities.rb
db/migrate/20180228152913_change_status_activities.rb
db/migrate/20180228153247_default_values_activities.rb
db/migrate/20180228155447_remove_total_price_bookings.rb
db/migrate/20180228155649_add_price_to_bookings.rb
db/migrate/20180228160459_add_timeslot_ref_to_bookings.rb
db/schema.rb
db/seeds.rb

- sync seeds
- add col status to timeslot
- update status archived / cancelled when needed
- update col name of activities from active to status
- confirm default 0 to price (and enum)
- update total_price into :monetize
- add dependent nullify
- add col timeslot in bookings
- seed a timeslot has many bookings

global-model-sync-and-crashtests

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
db/schema.rb

correct color bug for component

css-partial-components

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

@AlinaKhalilova 
added colors
added footer navbar cards css
added footer html

css-partial-card-footer-navbar

---

app/controllers/timeslots_controller.rb
app/models/activity.rb
app/views/activities/show.html.erb
app/views/timeslots/index.html.erb
app/views/timeslots/show.html.erb
config/locales/fr.yml
config/routes.rb
db/schema.rb
db/seeds.rb
test/fixtures/activities.yml

route, controller, view
+ added fr.yml

timeslots-show + fr.yml

---

app/views/layouts/application.html.erb

added HTML (header) for google result text & google result description & facebook (without facebook img card)

meta-header-2

---

app/controllers/activities_controller.rb
app/views/activities/index.html.erb
app/views/activity/index.html.erb
app/views/activity/new.html.erb
config/routes.rb

@EricBoutueil 
add route :index 
add method def index in activity controller
Create a view in activities
Thanks for your review

index-activity

---

app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
config/routes.rb

should be accessible from click in existing timeslot from agenda (last pull request form Sam needed)
---> /timeslots/52/bookings/new available (52 id to be confirmed with seed on computer)

nesting booking in timeslot

---

app/assets/stylesheets/components/_cards.scss
app/views/activities/show.html.erb

added css to compo "card" + changed img card in activities/show.html.erb   @solichon

css-compo-card

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/views/activities/new.html.erb
app/views/shared/_navbar.html.erb

Features done:
- Beg. Activity New Design (waiting Will for JS Channel aspect)
- Footer - Fixed bottom
- Navbar - FastUpdate

activity-new + footer-fixed

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/layouts/_general.scss
app/assets/stylesheets/layouts/_index.scss
app/views/activities/index.html.erb
app/views/activities/new.html.erb
app/views/activities/show.html.erb
app/views/bookings/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/timeslots/index.html.erb
app/views/timeslots/new.html.erb
app/views/timeslots/show.html.erb
lib/templates/erb/scaffold/_form.html.erb

@AlinaKhalilova @celinepernod @solichon 
J'ai souhaité avancé pour être plus serein demain. Il reste encore beaucoup à faire pour que ça soit explosif!

front containers and divs + links in home and navbar

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_fonts.scss
app/views/activities/index.html.erb
app/views/activities/new.html.erb
app/views/activities/show.html.erb
app/views/bookings/new.html.erb
app/views/timeslots/index.html.erb
app/views/timeslots/new.html.erb
app/views/timeslots/show.html.erb

titles-update

---

app/assets/stylesheets/components/_card_with_content.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/layouts/_general.scss
app/views/activities/index.html.erb
app/views/layouts/application.html.erb

index activities
+ container fixed

activities-index-front-finalization

---

app/assets/stylesheets/layouts/_general.scss
app/views/timeslots/show.html.erb
config/locales/activerecord.fr.yml
config/locales/fr.yml

Some changes to be made after will tutos (questions written for him in trello card)

timeslot-show-front

---

app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
config/locales/activerecord.fr.yml

english-word-chase

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/layouts/_general.scss
app/javascript/packs/application.js
app/models/timeslot.rb
app/views/timeslots/index.html.erb
app/views/timeslots/index.json.jbuilder

Update timeslot index
- tootip
- color

timeslot-index

---

app/assets/stylesheets/components/_activity.scss
app/views/activities/show.html.erb

btn aligned + tripadvisor img resized

show-activities-btn

---

app/controllers/bookings_controller.rb
app/controllers/timeslots_controller.rb
app/models/booking.rb
app/models/timeslot.rb

can be check on timeslots show

status calculated for timeslot, rest is ok

---

app/controllers/bookings_controller.rb
app/controllers/timeslots_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/application.js
app/models/booking.rb
app/views/bookings/new.html.erb
config/application.rb
package.json
yarn.lock

fix form (new/create)
boostrap select (live search) for clients
button fake new client
fix selection status + channel source
fixed layout

Booking new updates

---

config/application.rb
db/seeds.rb

added timezone + updated timings seeds

update timings seeds

---

app/controllers/timeslots_controller.rb
app/views/activities/index.html.erb
app/views/activities/new.html.erb
app/views/activities/show.html.erb
app/views/bookings/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/timeslots/new.html.erb
app/views/timeslots/show.html.erb

Repared forms and timeslot new + some front

Repared forms and timeslot new + some front

---

app/assets/stylesheets/components/_calendar.scss
app/javascript/packs/application.js
app/models/booking.rb
app/models/timeslot.rb
app/views/timeslots/index.html.erb
config/meta.yml

- meta
- fullacalendar (icon / title / color font)

fullcalendar / meta updated

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Logo un peu plus a gauche
message au lieu de client
sous titre: ajout col

Homepage fix mobile

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/models/booking.rb
app/views/bookings/new.html.erb
config/locales/activerecord.fr.yml

@EricBoutueil 
Button Nouveau: aligner avec la hauteur du simple form
Place disponible/complet : rouge
Selection du client :vert!
responsive design : button plus

bookings-new

---

app/controllers/bookings_controller.rb

error coming from translation of enum --> cannot use index anymore in controller

booking new save status source fixed
